extends:
  - react-app
  - react-app/jest
rules:
  arrow-spacing: error
  brace-style: error
  comma-spacing: error
  comma-style: error
  eol-last: error
  func-call-spacing: error
  indent:
    - error
    - 2
  jsx-quotes: error
  key-spacing: error
  keyword-spacing: error
  linebreak-style: error
  no-multi-spaces: error
  no-multiple-empty-lines: error
  no-tabs: error
  no-trailing-spaces: error
  nonblock-statement-body-position: error
  quotes: error
  semi: error
  semi-spacing: error
  semi-style: error
  space-before-blocks: error
  space-infix-ops: error
  space-unary-ops: error
